apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "fio_benchmark_exporter.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "fio_benchmark_exporter.name" . }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "fio_benchmark_exporter.name" . }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "fio_benchmark_exporter.name" . }}
            topologyKey: topology.kubernetes.io/zone
      {{- if .Values.podSecurityContext }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ template "fio_benchmark_exporter.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["fio_benchmark_exporter"]
        {{ if .Values.fioArgs }}
        args:
          {{- range .Values.fioArgs }}
          - {{ . | quote }}
          {{- end }}
        {{ end }}
        {{- if .Values.securityContext }}
        securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
        {{- end }}
        {{- if .Values.resources}}
        resources:
        {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: 9996
          protocol: TCP
          name: metrics
        {{- if eq .Values.volumeMode "Filesystem" }}
        volumeMounts:
        - mountPath: /mnt/fio-benchmark-exporter
          name: test-volume
        {{- else }}
        volumeDevices:
          - devicePath: /dev/sdx
            name: test-volume
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
      {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: test-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 260Gi
      volumeMode: {{ .Values.volumeMode }}
      storageClassName: {{ .Values.storageClassName }}
  serviceName: {{ template "fio_benchmark_exporter.name" . }}-headless-svc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fio_benchmark_exporter.name" . }}-headless-svc
  labels:
    app: {{ template "fio_benchmark_exporter.name" . }}
spec:
  ports:
    - port: 9996
      name: metrics
  clusterIP: None
  selector:
    app: {{ template "fio_benchmark_exporter.name" . }}